version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/html
  db:
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'fortbrasil_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql